name: CI

on: [push, pull_request]

jobs:
  lint:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: yarn
    - run: yarn lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: yarn
      - run: yarn test

  build-push-image:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build
        if: ${{ github.ref_name == 'develop' }}
        run: |
                docker build -f Dockerfile -t tauu/matrix-appservice-discord:latest .
      - name: Docker Build
        if: ${{ github.ref_type == 'tag' }}
        run: |
                docker build -f Dockerfile -t tauu/matrix-appservice-discord:${{github.ref_name}} .
      - name: Docker Push
        if: ${{ github.ref_name == 'main' }}
        run: |
                docker push tauu/matrix-appservice-discord:latest
      - name: Docker Push
        if: ${{ github.ref_type == 'tag' }}
        run: |
                docker push tauu/matrix-appservice-discordr:${{github.ref_name}}
